### ISSUE TITLE
"warning JSX not allowed in files with extension '.tsx'"

### ISSUE THREAD

**Issue by FakeYou** [strvcom/code-quality-tools#13]
I'm using `@strv/eslint-config-react` together with `@strv/eslint-config-typescript`. This combination is giving me the following error:

```
warning  JSX not allowed in files with extension '.tsx' react/jsx-filename-extension
```
 
For Typescript we want to override this rule to allow `tsx` extensions but I'm not sure if we should add it directly to the typescript ruleset as its not relevant for Node.js.

Maybe we can add a `@strv/eslint-config-typescript/react`?

**Comment by FakeYou** [comment]
`react/prop-types` is another that could be entirely turned off for typescript.

**Comment by robertrossmann** [comment]
I'd even suggest to drop the `react/jsx-filename-extension` rule completely. I vaguely recall a chat with someone from Frontend team that they do not want to use react components only in _.jsx_ files but also in _.js_ files. What matters most is how the project is compiled and not what extension is being used.

I'll drop the rule. Flow users would hit similar problem with their `.flow` extensions and I bet there are other compile-to-js languages which use JSX syntax with other, exotic file extensions. 🤷‍♂️

**Comment by robertrossmann** [comment]
As for `react/prop-types` I think it is best left to the user to turn the rule off. Solving for all possible permutations of rulesets x languages x project technologies could quite quickly blow on us. 💣 🔥 The easiest way to silence that rule for TS files would be to use an [`overrides[]`](https://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) stanza in _.eslintrc.js_ and disable that rule for all _.ts_ & _.tsx_ files. 🤔

**Comment by lazarofl** [comment]
You can just specify which extensions are allowed for this rule.

```json
{
    "rules": {
        "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".tsx"] }]
    }
}
