### ISSUE TITLE
[@strv/eslint-config-react] Replace babel-eslint with @babel/eslint-parser

### ISSUE THREAD

**Issue by GreatBasil** [strvcom/code-quality-tools#179]
babel-eslint has been deprecated. This package will no longer receive updates.

https://www.npmjs.com/package/babel-eslint

**Comment by robertrossmann** [comment]
Ooops! 😱 @GreatBasil are you up for a pull request? 😇

**Comment by dannytce** [comment]
I am gonna address it in #172 :)

**Comment by robertrossmann** [comment]
@dannytce you sure? That PR is big enough already... 💣

**Comment by dannytce** [comment]
@robertrossmann sure, it's a tiny thing. And kinda works well with the planned alpha release anyway - we can test it properly and publish it as a new major version :) 

Of course, from the easier review point of view, I can open a PR against #172 to review it separately.
