### ISSUE TITLE
Conflict between TypeScript & React ESLint rules

### ISSUE THREAD

**Issue by lucasconstantino** [strvcom/code-quality-tools#19]
So far, the recommended approach for enabling both **@strv/eslint-config-react** and **@strv/eslint-config-typescript** is that:

```
// .eslintrc.js
module.exports = {
  "extends": [
    "@strv/eslint-config-react",
    "@strv/eslint-config-typescript"
  ]
}
```

These base configurations do conflict in some aspects. I'm writing this issue while trying to properly configure code-quality-tools in a frontend project, and will add here these eventual conflicts and their solutions.

**Comment by lucasconstantino** [comment]
## Extensions

**@strv/eslint-config-react** builds on top of **@strv/eslint-config-base**, which states:

```
// simplified .eslintrc setting path
"settings.import/resolver.node.extensions": [".mjs", ".es", ".js", ".jsx", ".json", ".node"]
```
**@strv/eslint-config-react** also builds on top of **@strv/eslint-config-base**, but overrides this setting as follows:

```
// simplified .eslintrc setting path
"settings.import/resolver.node.extensions": [".ts", ".d.ts", ".mjs", ".js", ".json"]
```

This difference is:

```diff
+ .ts
+ .d.ts
- .jsx
- .es
- .node
```

So far as I've searched, there is no way to perform _combination_ of settings. Therefore, in order to use @strv/eslint-config-react and @strv/eslint-config-typescript together the current solution is to override this setting at the project's `.eslintrc.js`, such as follows:

```js
// .eslintrc.js
'use strict'

modulex.exports = {
  extends: [
    '@strv/eslint-config-react',
    '@strv/eslint-config-typescript',
  ],
  settings: {
    'import/resolver': {
      node: {
        extensions: [
          '.js',
          '.json',
          '.ts',
          '.d.ts',
          '.mjs',
          '.es',
          '.node',
          '.jsx',
          '.tsx',
        ],
      },
    },
  },
}

```

**Comment by dannytce** [comment]
I think we should go ideally with `eslint-config-typescript-react` which will be importing needed stuff under the hood and extending needed rules

**Comment by lucasconstantino** [comment]
@dannytce you meen creating a new config?

**Comment by dannytce** [comment]
Yes please :) We are probably going to do that. Need to double check that with @robertrossmann and @prichodko

**Comment by robertrossmann** [comment]
@lucasconstantino When using TS language in combination with React, what are the module extensions that you need to be recognised?

For `base`, I think with the advent of Node.js 12 the "officially" supported extensions for a basic javascript are:

- `.mjs`
- `.cjs`
- `.js`
- `.json`
- `.node`

For `react`, the above remains, plus

- `.jsx`

For `typescript`, the `base` remains, plus

- `.ts`
- `.d.ts`
- `.tsx`

Is is needed for TypeScript to also recognise `.jsx`? Is `.jsx` a recognised file extension by the TypeScript compiler?

I am envisioning a relatively simple solution where we would simply extend this configuration value from `base` with some extra extensions and that should cover 99.9% of use cases.

**Comment by lucasconstantino** [comment]
@robertrossmann as far as I know, `.jsx` is not interpreted by TypeScript, but should certainly be resolved by ESLint: there is nothing preventing someone to have acutal `.jsx` files in a TypeScript based application, nor should there be - the same as we expect for `.js` files. The confusion here is that TypeScript does support JSX files out-of-the-box, which is rather opinionated.

@robertrossmann I've tried to tweak if `.eslintrc.js` files in order to properly _extend_ configs, but the only way that seems to be possible is to actually import the configuration from the other file - which would be redundant with the `extends` key.

I've also tried to "resolve" the whole ESLint config using ESLint's API, but didn't dive much into it... there is a command line argument `--print-config` which does what I want: get a full, final ESLint config, which we could then programmatically extend, but the command is rather complex and it's logic doesn't seem to be available as an API.

Nonetheless, I totally agree with the idea of extending the real `base` config, just giving you a heads up on what this might mean.

**Comment by robertrossmann** [comment]
@lucasconstantino The problem with extensions should now be fixed in the latest versions of rulesets.

Please note that:

- ESLint will only lint those files whose extensions are provided on the commandline, only `.js` is linted by default
- ESLint will use the parser and rules defined in your _eslintrc_ file for all file types, unless you override the configuration for those files using the `overrides: []` feature. I am not sure if it is possible to override the parser, so it might be difficult to lint both vanilla JS & TS sources in one go, or any other combination of source types.

Let me know if I can help with your setup or if you discover any other incompatibilities or conflicts between these two rulesets. The way you include the rulesets was the intended usage and if something does not work it's a boog. 🐛

**Comment by robertrossmann** [comment]
@lucasconstantino I am going to close this issue as I believe the inconsistencies you reported have been fixed. In case you find more please do let us know so we can fix them all for everyone! ❤️ Thanks!
