### ISSUE TITLE
Migration tutorial improvement

### ISSUE THREAD

**Issue by martinstepanek** [strvcom/code-quality-tools#191]
Hi! 

Firstly I would like to thank you for providing [migration tutorial](https://github.com/strvcom/code-quality-tools/blob/master/documentation/eslint/migration.md)! 

I would suggest mentioning [this issue](https://github.com/strvcom/strv-react-scripts/issues/22) in that tutorial, specifically that this new package is not compatible with `@strv/react-scripts` v3.0.0

**Comment by dannytce** [comment]
Hey @martinstepanek! Thank you for bringing this in :) Definitely a great suggestion. Tho I believe we are not using `@strv/react-scripts` anymore and should deprecate it soon :)

Btw if you are starting a new project, feel free to try out new alpha releases (available with @next, for example ) - these are the most up to date rules :)

**Comment by robertrossmann** [comment]
We just marked the `@strv/react-scripts` package as deprecated and archived the repo. 💣 🔥
