### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by dannytce** [strvcom/code-quality-tools#2]
iOS guys are using https://fastlane.tools/ :) I think before we jump into CLI development, we should examine, what is the correct way, so it could be used universally on any platform.

**Comment by dannytce** [comment]
So I was thinking it's about a time to revisit this issue.

I just came across this wonderful thing: https://github.com/spotify/web-scripts 

I know that @lucasconstantino played around with [sapegin/mrm](https://github.com/sapegin/mrm)

And @developer239 has his [opinionated app generator](https://github.com/developer239/create-opinionated-app). 

Perhaps let's put our heads together and create some stuff! :)

**Comment by lucasconstantino** [comment]
First thing should be defining what this CLI would be addressing... nevertheless, if it's supposed to be an more general purposed tool, there are plenty of framework solutions out there, from which I quote two I've used:

- [oclif](https://github.com/oclif/oclif);
- [Commander.js](https://github.com/tj/commander.js);

I like the first: it's very simple and clean to use, with good TypeScript support.

**Comment by robertrossmann** [comment]
I think the scope of this project should remain in the area of shared configuration for existing tools.
