### ISSUE TITLE
[commitlint-config] Inconsistency with company Git guidelines

### ISSUE THREAD

**Issue by ythecombinator** [strvcom/code-quality-tools#34]
[The rules for this package](https://github.com/strvcom/code-quality-tools/blob/master/packages/commitlint-config/index.js#L14) extend [config-conventional from commitlint authors](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional). It turns out that [our Git guidelines](https://github.com/strvcom/strv-guidelines/blob/master/git.md#commit-messages) state that we should [*Capitalize the subject line*](https://github.com/strvcom/strv-guidelines/blob/master/git.md#commit-messages). `config-conventional`, on the other hand, sets this as [never](https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional#subject-case).

The result is: if we follow our convention, having `commitlint-config` set, we get stuck in a `commit-msg` hook 🤷. 

We should consider picking either on or the other.

**Comment by robertrossmann** [comment]
My personal belief is that we should adopt conventional-commits.

This is being addressed in https://github.com/strvcom/strv-guidelines/pull/2

**Comment by robertrossmann** [comment]
This was addressed in [this commit](https://github.com/strvcom/strv-guidelines/commit/94cb7adaca529a930f872e02c50ee34943c3e8cd) - you can now choose on a per-project basis to either follow conventional-commits or our own guidelines. 🎉 🍻 

Thanks for the suggestion!
