### ISSUE TITLE
[eslint-config-base] Configuration for rule "import/no-useless-path-segments" is invalid

### ISSUE THREAD

**Issue by ythecombinator** [strvcom/code-quality-tools#35]
If I manage to add either `@strv/react-native/style` or `@strv/eslint-config-typescript/style` to my `.eslintrc`, I get this error:

```
Error: ../../.eslintrc.js » @strv/eslint-config-react-native/style » /Users/matheusalbuquerque/Documents/dev/strv/goulash-club/Repos/goulash-club-frontend/node_modules/@strv/eslint-config-react/style.js » /Users/matheusalbuquerque/Documents/dev/strv/goulash-club/Repos/goulash-club-frontend/node_modules/@strv/eslint-config-base/style.js:
	Configuration for rule "import/no-useless-path-segments" is invalid:
	Value {"noUselessIndex":true} should NOT have additional properties.
```

I checked the [source](https://github.com/strvcom/code-quality-tools/blob/master/packages/eslint-config-base/style.js#L598) and it seems to be just like to documentation [reccomends](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-useless-path-segments.md#nouselessindex) – so, for now, I don't have any clue 😞 .

**Comment by robertrossmann** [comment]
Sometimes this happens when the ruleset requires a newer version of ESLint than what is currently installed. When you do `npm ls eslint` and compare the installed version with `npm info eslint version`, are you seeing at least the same semver-major versions?

**Comment by robertrossmann** [comment]
Oh sorry, this comes from the `eslint-plugin-import` so we must check the installed version of that package, not that of ESLint.

Please compare `npm info @strv/eslint-config-base dependencies` semver range with that of what you have installed locally: `npm ls eslint-config-import`. 🙏 You should see at least the same or newer version in the latter output.

**Comment by robertrossmann** [comment]
@ythecombinator I will close this issue due to inactivity but if you are still experiencing the problem please re-open and we'll have another look. Thanks! ❤️
