### ISSUE TITLE
@strv/eslint-config-react: decide on new rules & new rule options

### ISSUE THREAD

**Issue by robertrossmann** [strvcom/code-quality-tools#37]
### [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y)
See [control-has-associated-label](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/control-has-associated-label.md) docs and decide whether or not we should enable this rule. 🙏

The rule is part of [v6.2.0 release](https://github.com/evcohen/eslint-plugin-jsx-a11y/releases/tag/v6.2.0).

### [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react)

A lot. See the release notes for [v7.13 & v7.14](https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md#7130---2019-05-03).

### [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)

Uhm, dunno? They do not provide a changelog for that package. 🤷‍♂ 🤦‍♂ The relevant changes are since v1.5.

**Comment by dannytce** [comment]
Thank you @robertrossmann for putting this together :) We will take a look with @prichodko hopefully soon enough :)

Btw this is exactly the usecase, where #23 could help us :)

**Comment by robertrossmann** [comment]
Fixed in e9ae66d4a284f00e944709ae3f4857abcea3e6f8.
