### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by dannytce** [strvcom/code-quality-tools#42]
There is snyk, there is this little guy: https://github.com/lirantal/is-website-vulnerable

Should we consider adding these tools to this monorepo?

**Comment by lirantal** [comment]
If I can help let me know.
Perhaps consider lockfile-lint too, as a reading reference see this: https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/

**Comment by dannytce** [comment]
Hey @lirantal! Thank you very much for pointing out lockfile-lint!

No help needed at this point, but if we will have any struggles, we will definitely ping you. Thank you again!

**Comment by lirantal** [comment]
Sure thing! 🤗

**Comment by developer239** [comment]
Resolved in #106
