### ISSUE TITLE
Rework stylelint-config-styled-components to a generic stylelint ruleset

### ISSUE THREAD

**Issue by robertrossmann** [strvcom/code-quality-tools#7]
The `stylelint` tool supports linting raw CSS and Less files. We should make use of it!

Let's rename `stylelint-config-styled-components` to just `stylelint-config` and add a generic configuration for CSS and Less, and then add a `styled-components` ruleset which would enable support for style-in-js patterns. 👍

**Comment by developer239** [comment]
`raw CSS and Less files` how is that useful when all projects in STRV use styled-components? Wouldn't that be like using `@strv/eslint-config-node` and `@strv/eslint-config-react` in CSR React application?
