### ISSUE TITLE
Use correct rule for TypeScript

### ISSUE THREAD

**Issue by prichodko** [strvcom/code-quality-tools#83]
We need to use `@typescript-eslint/no-unused-expressions` instead of ESlint `no-unused-expressions `, because it can't handle optional chaining.

This code emits warning `Expected an assignment or function call and instead saw an expression`.
```js
fn?.('hello')
```

Related:
https://github.com/typescript-eslint/typescript-eslint/issues/1241#issuecomment-556027910

**Comment by robertrossmann** [comment]
Thanks, fixed in [`2.3.0`](https://github.com/strvcom/code-quality-tools/blob/master/packages/eslint-config-typescript/CHANGELOG.md#230-2020-03-03) 🎉
