### ISSUE TITLE
Possible improvements [config-react-native]

### ISSUE THREAD

**Issue by developer239** [strvcom/code-quality-tools#97]
Hello 👋 
this is the third batch of possible improvements.

**Missing rules:**

This one is complete. 🎉 🎉 

**Rules that I would change:**
Mostly config code style improvement so feel free to ignore.

- [react-native/no-unused-styles](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-unused-styles.md) error
- [react-native/no-inline-styles](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-inline-styles.md) error
- [react-native/no-color-literals](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-color-literals.md) error
- [react-native/no-raw-text](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-raw-text.md) 0 😄 actually I turned this off. turns out my config is not that strict after all 😂 
- [react-native/no-single-element-style-arrays](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-single-element-style-arrays.md) error

**Comment by xhudec** [comment]
Thanks for suggestions @developer239 🚀

I agree with [react-native/no-single-element-style-arrays](https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-single-element-style-arrays.md).

But others I would leave as warnings. It just feels right.

**Comment by developer239** [comment]
Seeing that this PR wouldn't add any rules we can leave it as it is. Although if anyone wants to make it more strict let me know I will fix it in the future. 🙂 

- react-native/no-unused-styles: there is no reason to keep legacy code in codebase we can always recover old styles from git
- react-native/no-inline-styles: I write inline styles when I am lazy to create a variable or use react-native stylesheet (which is better for app performance than object)
-  react-native/no-color-literals: I agree that changing this might be too strict
- react-native/no-single-element-style-arrays: I have actually never needed this
