### ISSUE TITLE
Possible improvements [config-typescript]

### ISSUE THREAD

**Issue by developer239** [strvcom/code-quality-tools#99]
Hello 👋 
last update.

![party](https://user-images.githubusercontent.com/14946081/80642770-5032ea00-8a67-11ea-8a5b-89256f8a2ef2.gif)

**Missing rules:**
- [@typescript-eslint/ban-ts-ignore](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-ignore.md) warn (funny how I set everything to error but I leave this as warn isn't it? 😅🙉)
- [@typescript-eslint/camelcase](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/camelcase.md) warn (I would love to set this as an error but apollo code gen...)
- [@typescript-eslint/class-name-casing](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/class-name-casing.md) error
- [generic-type-naming](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/generic-type-naming.md) error **[major]** (this one is deprecated I will investigate `naming-convention` but this is one of my favorite finds 🙂)
- [@typescript-eslint/no-magic-numbers](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-magic-numbers.md) warn (I turned this off because it was impossible to use it in existing projects it might be interesting to set this to warn for new projects 🙉 )

**Missing plugins:**
- [eslint-plugin-unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports) (this thing is amazing 👌)

**Missing rules from missing plugins:**
- unused-imports/no-unused-imports 0
- unused-imports/no-unused-imports-ts 2
- unused-imports/no-unused-vars
- unused-imports/no-unused-vars-ts

**Rules that I would change:**
- [@typescript-eslint/array-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md) error, array
- [@typescript-eslint/await-thenable](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md) error
- [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md) error (very useful rule that forces to catch errors or use await for promises)
- [@typescript-eslint/no-for-in-array](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-for-in-array.md) 0
- [@typescript-eslint/no-misused-new](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-new.md) error
- [no-misused-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) error
- [@typescript-eslint/no-parameter-properties](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-parameter-properties.md) 0 (important in [nest.js)](https://nestjs.com/)
- [@typescript-eslint/no-this-alias](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-this-alias.md) error
- [@typescript-eslint/no-unnecessary-qualifier](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-qualifier.md) error
- [@typescript-eslint/no-unnecessary-type-assertion](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md) error
- [@typescript-eslint/no-unused-vars](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) 0 (I think this needs to be off for the plugin to work)
- [@typescript-eslint/promise-function-async](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/promise-function-async.md) 0
- [@typescript-eslint/require-await](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md) error 🙉 
- [@typescript-eslint/restrict-template-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-template-expressions.md) 0
- [@typescript-eslint/prefer-function-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-function-type.md) error
- [@typescript-eslint/prefer-includes](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-includes.md) error
- [@typescript-eslint/prefer-nullish-coalescing](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md) error (autofixable)
- [@typescript-eslint/prefer-optional-chain](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-optional-chain.md) error (autofixable)
- [@typescript-eslint/prefer-string-starts-ends-with](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-string-starts-ends-with.md) error
- 

**For fun:**
- [@typescript-eslint/no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md) 0 (I have this one off 😅)
- [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) 0 (actually I turned this off 🙂)
- [@typescript-eslint/explicit-member-accessibility](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md) 0 (I turned this off as well 😮)

Two new errors for me. 😂

**Comment by xhudec** [comment]
Woah, what a ride! Great suggestions again @developer239 

## Missing rules

- [@typescript-eslint/ban-ts-ignore](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-ts-ignore.md) warn
    - redundant with `'@typescript-eslint/ban-ts-comment': 'warn'`
- [@typescript-eslint/camelcase](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/camelcase.md) warn
    - agree!
- [@typescript-eslint/class-name-casing](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/class-name-casing.md) error
    - agree, `warn` at least
- [generic-type-naming](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/generic-type-naming.md) error **[major]**
    - agree, `warn` at least
- [@typescript-eslint/no-magic-numbers](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-magic-numbers.md) warn
    - agree, but I would suggest to turn `ignoreEnums: true` because I don't see a reason why this should be considered as "bad" to put numbers in Enums

## Missing plugins

Already discussed in [https://github.com/strvcom/code-quality-tools/issues/95](https://github.com/strvcom/code-quality-tools/issues/95)

## Change proposals

- [@typescript-eslint/array-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/array-type.md) error, array
    - warn should be enough
    - I would also vote for `array` instead of `array-simple`
- [@typescript-eslint/await-thenable](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/await-thenable.md) error
    - agree
- [@typescript-eslint/no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md) error
    - warn should be enough
- [@typescript-eslint/no-for-in-array](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-for-in-array.md) 0
    - 🤷‍♂️
- [@typescript-eslint/no-misused-new](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-new.md) error
    - warn should be enough, although `error` might do the thing
- [no-misused-promises](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-misused-promises.md) error
    - agree
- [@typescript-eslint/no-parameter-properties](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-parameter-properties.md) 0 (important in [nest.js)](https://nestjs.com/)
    - 🤷‍♂️not sure
- [@typescript-eslint/no-this-alias](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-this-alias.md) error
    - 🤔agree
- [@typescript-eslint/no-unnecessary-qualifier](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-qualifier.md) error
    - warn should be enough
- [@typescript-eslint/no-unnecessary-type-assertion](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unnecessary-type-assertion.md) error
    - warn should be enough
- [@typescript-eslint/no-unused-vars](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md) 0
    - I guess you reference plugin as `no-unused-imports`?
    - What's the behavior when there is an variable which is not used?
- [@typescript-eslint/promise-function-async](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/promise-function-async.md) 0
    - 🤷‍♂️not sure
- [@typescript-eslint/require-await](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/require-await.md) error
    - agree
- [@typescript-eslint/restrict-template-expressions](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/restrict-template-expressions.md) 0
    - I had to adjust this one on personal projects as well as this was really annoying
    - so maybe just adjust config of this one?

    ```
    'warn',
    {
      allowNumber: true,
    },
    ```

- [@typescript-eslint/prefer-function-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-function-type.md) error
    - mhm, warn seems to be enough
- [@typescript-eslint/prefer-includes](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-includes.md) error
    - warn seems enough
- [@typescript-eslint/prefer-nullish-coalescing](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-nullish-coalescing.md) error
    - warn seems enough
- [@typescript-eslint/prefer-optional-chain](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-optional-chain.md) error
    - warn seems enough
- [@typescript-eslint/prefer-string-starts-ends-with](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-string-starts-ends-with.md) error
    - warn seems enough

## Funny ones

- [@typescript-eslint/no-explicit-any](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-explicit-any.md) 0
    - should remain as `warn` !
- [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) 0
    - I disabled it as well 😅
    - it was too annoying to write an extra `React.ReactNode` or `JSX.Element` to React's function components return type
- [@typescript-eslint/explicit-member-accessibility](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-member-accessibility.md) 0
    - should remain as `warn`

## My Notes

- [@typescript-eslint/prefer-readonly-parameter-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md) 0
    - [https://github.com/strvcom/code-quality-tools/issues/96#issuecomment-623446986](https://github.com/strvcom/code-quality-tools/issues/96#issuecomment-623446986) - my comment & screenshots regarding `react/prefer-read-only-props`
- [@typescript-eslint/explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md) 0
    - similar as [explicit-function-return-type](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-function-return-type.md) - too annoying
- [@typescript-eslint/naming-convention](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/naming-convention.md) 0
    - I think I have it disabled because I was defining components via `function` and it was shouting at me because of PascalCase is not allowed for function names
- [@typescript-eslint/member-ordering](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-ordering.md)
    - It had conflicts with my personal 😇ordering system 😅

cc @robertrossmann @dannytce

**Comment by developer239** [comment]
@xhudec Thank you for the review. It looks like we are late to the party and most of the rules that I proposed are replaced by `class-name-casing`. 🙂 

Anyway, I created #105  with two changes. I noticed that there are some todos from @robertrossmann so I will leave `warn` -> `error` for later.

**Comment by robertrossmann** [comment]
I believe about 95% of your pain points mentioned here have been addressed via 3c5397009d41f22762cc748fdd4bfb86896f05a5. 🎉 🚀
